/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CreateLotForm: typeof import('./src/components/CreateLotForm.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
